name: Test C++ application

on:
    push:
        paths:
            - "**.cpp"
            - "**.h"
    pull_request:
        paths:
            - "**.cpp"
            - "**.h"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Compile the Swirl compiler
              run: g++ core/swirl.cpp -o core/swirl

            - name: Run the compiler
              run: cd core && ./swirl
